name: Conflict Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conflict-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Fetch all branches to compare against
      - name: Fetch all branches
        run: git fetch --all

      # Step 3: Check for merge conflicts with the base branch (main)
      - name: Check for Merge Conflicts with Main
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}  # Checkout the base branch (main)
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch  # Fetch the PR head branch
          git merge --no-commit --no-ff pr-branch || exit 1  # Merge the PR branch into the base branch and check for conflicts

      # Step 4: Check for conflicts with GitHub Pages branch (gh-pages)
      - name: Check for Conflicts with GitHub Pages (gh-pages)
        if: success()  # Only run this if the previous step passed
        run: |
          git fetch origin gh-pages || echo "No gh-pages branch found"
          git checkout gh-pages || echo "Unable to checkout gh-pages, skipping."
          git merge --no-commit --no-ff pr-branch || exit 1
